### ISSUE TITLE
os debug build won't launch

### ISSUE THREAD

**Issue by Osanosa** [diia-open-source/android-diia#9]
```
00:21:52.516 WM-WorkerFactory         E  Could not instantiate ua.gov.diia.core.util.work.DoApplicationSettingsProvisionWork (Ask Studio Bot)
                                         java.lang.NoSuchMethodException: ua.gov.diia.core.util.work.DoApplicationSettingsProvisionWork.<init> [class android.content.Context, class androidx.work.WorkerParameters]
                                         	at java.lang.Class.getConstructor0(Class.java:3325)
                                         	at java.lang.Class.getDeclaredConstructor(Class.java:3063)
                                         	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
                                         	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
                                         	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
                                         	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                         	at java.lang.Thread.run(Thread.java:1012)
00:21:52.516 WM-WorkerWrapper         E  Could not create Worker ua.gov.diia.core.util.work.DoApplicationSettingsProvisionWork
00:21:52.544 WM-WorkerFactory         E  Could not instantiate ua.gov.diia.core.util.work.CheckAppVersionUpdatedWork (Ask Studio Bot)
                                         java.lang.NoSuchMethodException: ua.gov.diia.core.util.work.CheckAppVersionUpdatedWork.<init> [class android.content.Context, class androidx.work.WorkerParameters]
                                         	at java.lang.Class.getConstructor0(Class.java:3325)
                                         	at java.lang.Class.getDeclaredConstructor(Class.java:3063)
                                         	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
                                         	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
                                         	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
                                         	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                         	at java.lang.Thread.run(Thread.java:1012)
00:21:52.544 WM-WorkerWrapper         E  Could not create Worker ua.gov.diia.core.util.work.CheckAppVersionUpdatedWork
00:21:53.302 WM-WorkerFactory         E  Could not instantiate ua.gov.diia.notifications.work.SendPushTokenWork (Ask Studio Bot)
                                         java.lang.NoSuchMethodException: ua.gov.diia.notifications.work.SendPushTokenWork.<init> [class android.content.Context, class androidx.work.WorkerParameters]
                                         	at java.lang.Class.getConstructor0(Class.java:3325)
                                         	at java.lang.Class.getDeclaredConstructor(Class.java:3063)
                                         	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
                                         	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
                                         	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
                                         	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                         	at java.lang.Thread.run(Thread.java:1012)
00:21:53.303 WM-WorkerWrapper         E  Could not create Worker ua.gov.diia.notifications.work.SendPushTokenWork

```
![image](https://github.com/diia-open-source/android-diia/assets/80209416/8ce8d598-7098-4feb-8f56-bf548512ec44)

**Comment by Osanosa** [comment]
Also i hate fragments

**Comment by SN4S** [comment]
You can remove "oss" from url's in build.gradle file, like i did
![image](https://github.com/diia-open-source/android-diia/assets/43933045/43111ef7-8084-47a5-8135-45b34b803650)
